# https://pre-commit.com/
ci:
    autofix_commit_msg: 'ci: auto fixes from pre-commit.com hooks'
    autoupdate_commit_msg: 'ci: pre-commit autoupdate'

# prepare-commit-msg is used by hook id: check-message
default_install_hook_types: [pre-commit, prepare-commit-msg]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: [--max-line-length=100, --ignore=E501]
        exclude: ^commit_check/__init__.py
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
        exclude: ^testing/resources/
-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    -   id: codespell
-   repo: https://github.com/commit-check/commit-check
    rev: v0.7.4
    hooks:
    -   id: check-message
    # -   id: check-branch          # uncomment if you need.
    # -   id: check-author-name     # uncomment if you need.
    # -   id: check-author-email    # uncomment if you need.
    # -   id: commit-signoff        # uncomment if you need.
